# Trigger when commits are pushed to the master branch

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  searcher-release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Checkout go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' # The Go version to download (if necessary) and use.

    - name: Go version
      id: Version
      run: go version

    - name: Go download
      run: go mod download

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      id: vars
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        INITIAL_VERSION: 0.1.0
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: patch

    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}


